append_unmatched: true
flatten_single_child_sections: true
nav:
  - Home: index.md
  - Principles:
    - DHCW:
      - Introduction: principles/index.md
      - Principles: principles/
  - Design Authority:
    - DHCW:
      - Introduction: design-authority/index.md
      - Decision Template: design-authority/dhcw/architecture-decision-record-template.md
      - Decision Process: design-authority/dhcw/architecture-decision-record-process/index.md
      - Design Template: design-authority/dhcw/architecture-design-overview-template.md
      - ToR: design-authority/dhcw/terms-of-reference/
      - Meetings: design-authority/dhcw/meetings/
      - Enterprise Architecture Metamodel:
        - design-authority/ea-metamodel/index.md
        - Metamodel Decisions: design-authority/ea-metamodel/ 
  - Decisions:
    - DHCW:
      - Introduction: decisions/index.md
      - Meta Decisions: decisions/meta-decisions/
      - Process Decisions: decisions/process-decisions/
      - Technical Decisions: decisions/technical-decisions/